spring.application.name=FYP2
spring.config.import=optional:file:.env[.properties]   
logging.level.org.springframework.security=TRACE
logging.level.com.example.FYP2.Config.JWTAuthFilter=DEBUG

spring.jpa.hibernate.ddl-auto=update
spring.datasource.url=${DB_URL}
spring.datasource.username=${DB_USERNAME}
spring.datasource.password=${DB_PASSWORD}
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver
SecretKey=${JWT_SECRET} 


spring.mail.host=smtp.gmail.com
spring.mail.port=587
spring.mail.username=${Sender_Mail}
spring.mail.password=${Mail_PASSWORD}
spring.mail.properties.mail.smtp.auth=true
spring.mail.properties.mail.smtp.starttls.enable=true
spring.mail.properties.mail.smtp.starttls.required=true

